M48
; DRILL file {KiCad 9.0.1} date 2025-11-13T12:10:01-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-13T12:10:01-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X1.8231Y-3.1937
X2.0507Y-3.1937
T2
X1.1024Y-3.2283
X1.8307Y-1.7717
X2.5591Y-2.5
M30
